name: CICD FRONT to AWS S3 

# trigger 
on:
  push:
    branches:
      - main

jobs:
  deploy: # job 이름
    runs-on: ubuntu-latest #os 설정 

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3 # 업로드된 코드를 가져옴 
      
      - name: 리액트 빌드 
        working-directory: ./
        run: |
          npm install
          npm run build 

      - name: AWS IAM 사용자 설정 
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}} 
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}} 
          aws-region: ${{secrets.AWS_REGION}}

      - name: S3에 업로드 
        working-directory: ./
        run: aws s3 sync ./build s3://leeejjjubucket --acl public-read 
